language: python
dist: xenial
sudo: required
cache:
- pip
- directories:
  - $HOME/.ccache
python:
- 3.8
env:
  global:
    AUDIODEV=null
    CC=gcc
    CCACHE_COMPRESS=1
    CCACHE_SLOPPINESS=pch_defines,time_macros
    CXX=g++
    MYPYPATH=/tmp/typehints
    PATH=/usr/lib/ccache:$PATH
    SUPERCOLLIDER_REPO=josiah-wolf-oberholtzer/supercollider
    SUPERCOLLIDER_VERSION=extend-node-info-response
    USE_CCACHE=1
addons:
  apt:
    packages:
    - alsa-oss
    - alsa-utils
    - build-essential
    - cmake
    - espeak
    - ffmpeg
    - g++-4.9
    - gcc-4.9
    - graphviz 
    - jackd2
    - lame
    - libasound2-dev
    - libavahi-client-dev
    - libfftw3-dev
    - libicu-dev
    - libjack-jackd2-dev
    - libreadline6-dev
    - libsndfile1-dev
    - libudev-dev
    - libxt-dev
    - pkg-config
before_install:
- make -C .travis/ get-type-hints
- make -C .travis/ setup-audio
- make -C .travis/ install-scsynth
- scsynth -v
install:
- pip install https://github.com/josiah-wolf-oberholtzer/supriya/archive/master.zip
- pip install cython
- pip install -e .[test]
before_script:
- sudo -E su $USER -c "jackd -r -ddummy -r44100 -p1024" 2>/dev/null &
- sleep 5  # give jackd time to start
- sudo -E su $USER -c "scsynth -D 0 -H dummy -R 0 -u 57110" &
- sleep 5
- killall scsynth
script:
- make black-check
- make flake8
- make mypy
- sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; make -C .travis/ sanity-check"
- sudo -E su $USER -c "source $VIRTUAL_ENV/bin/activate; make -C .travis/ pytest"
notifications:
  email: false
